package fr.ekinci.distributedpool.corba;


/**
* fr/isidis/pw/impl/distributedpool/corba/SqlConnectionLicenseServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SqlConnectionLicenseService.idl
* dimanche 19 avril 2015 11 h 44 CEST
*/

public interface SqlConnectionLicenseServiceOperations 
{
  fr.ekinci.distributedpool.corba.SqlNodeInformation[] getConnectionInformation (String login, String password);
} // interface SqlConnectionLicenseServiceOperations
