package fr.ekinci.distributedpool.corba;

/**
* fr/isidis/pw/impl/distributedpool/corba/SqlConnectionLicenseServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SqlConnectionLicenseService.idl
* dimanche 19 avril 2015 11 h 44 CEST
*/

public final class SqlConnectionLicenseServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public fr.ekinci.distributedpool.corba.SqlConnectionLicenseService value = null;

  public SqlConnectionLicenseServiceHolder ()
  {
  }

  public SqlConnectionLicenseServiceHolder (fr.ekinci.distributedpool.corba.SqlConnectionLicenseService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = fr.ekinci.distributedpool.corba.SqlConnectionLicenseServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    fr.ekinci.distributedpool.corba.SqlConnectionLicenseServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return fr.ekinci.distributedpool.corba.SqlConnectionLicenseServiceHelper.type ();
  }

}
