package fr.ekinci.distributedpool.corba;


/**
* fr/isidis/pw/impl/distributedpool/corba/SqlConnectionLicenseService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SqlConnectionLicenseService.idl
* dimanche 19 avril 2015 11 h 44 CEST
*/


public interface SqlConnectionLicenseService extends SqlConnectionLicenseServiceOperations , org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SqlConnectionLicenseService
