package fr.ekinci.distributedpool.corba;


/**
* fr/isidis/pw/impl/distributedpool/corba/SqlNodeInformation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SqlConnectionLicenseService.idl
* dimanche 19 avril 2015 11 h 44 CEST
*/

public final class SqlNodeInformation implements org.omg.CORBA.portable.IDLEntity
{
  public String nodeIp = null;
  public int nodePort = (int)0;
  public String driverName = null;
  public int numberOfConnectionPerDataSource = (int)0;

  public SqlNodeInformation ()
  {
  } // ctor

  public SqlNodeInformation (String _nodeIp, int _nodePort, String _driverName, int _numberOfConnectionPerDataSource)
  {
    nodeIp = _nodeIp;
    nodePort = _nodePort;
    driverName = _driverName;
    numberOfConnectionPerDataSource = _numberOfConnectionPerDataSource;
  } // ctor

} // class SqlNodeInformation
