package fr.ekinci.distributedpool.corba;


/**
* fr/isidis/pw/impl/distributedpool/corba/TabSqlNodeInformationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SqlConnectionLicenseService.idl
* dimanche 19 avril 2015 11 h 44 CEST
*/

public final class TabSqlNodeInformationHolder implements org.omg.CORBA.portable.Streamable
{
  public fr.ekinci.distributedpool.corba.SqlNodeInformation value[] = null;

  public TabSqlNodeInformationHolder ()
  {
  }

  public TabSqlNodeInformationHolder (fr.ekinci.distributedpool.corba.SqlNodeInformation[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = fr.ekinci.distributedpool.corba.TabSqlNodeInformationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    fr.ekinci.distributedpool.corba.TabSqlNodeInformationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return fr.ekinci.distributedpool.corba.TabSqlNodeInformationHelper.type ();
  }

}
