package fr.ekinci.distributedpool.corba;


/**
* fr/isidis/pw/impl/distributedpool/corba/TabSqlNodeInformationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SqlConnectionLicenseService.idl
* dimanche 19 avril 2015 11 h 44 CEST
*/

abstract public class TabSqlNodeInformationHelper
{
  private static String  _id = "IDL:fr/isidis/pw/impl/distributedpool/corba/TabSqlNodeInformation:1.0";

  public static void insert (org.omg.CORBA.Any a, fr.ekinci.distributedpool.corba.SqlNodeInformation[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static fr.ekinci.distributedpool.corba.SqlNodeInformation[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = fr.ekinci.distributedpool.corba.SqlNodeInformationHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (fr.ekinci.distributedpool.corba.TabSqlNodeInformationHelper.id (), "TabSqlNodeInformation", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static fr.ekinci.distributedpool.corba.SqlNodeInformation[] read (org.omg.CORBA.portable.InputStream istream)
  {
    fr.ekinci.distributedpool.corba.SqlNodeInformation value[] = null;
    int _len0 = istream.read_long ();
    value = new fr.ekinci.distributedpool.corba.SqlNodeInformation[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = fr.ekinci.distributedpool.corba.SqlNodeInformationHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, fr.ekinci.distributedpool.corba.SqlNodeInformation[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      fr.ekinci.distributedpool.corba.SqlNodeInformationHelper.write (ostream, value[_i0]);
  }

}
